// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbWO0loW2Throqo1tt6HZuGesdu_q-AH8',
    appId: '1:516346071617:web:b990d38036e64bdc4a14c0',
    messagingSenderId: '516346071617',
    projectId: 'aviation-project-46322',
    authDomain: 'aviation-project-46322.firebaseapp.com',
    storageBucket: 'aviation-project-46322.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbqpdoGTvn-GpdbjZGLHx5WPFdJ7zNOJQ',
    appId: '1:516346071617:android:24f3935bc74de2f34a14c0',
    messagingSenderId: '516346071617',
    projectId: 'aviation-project-46322',
    storageBucket: 'aviation-project-46322.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR83I1XGeJUjiMKTEe9sw34dYl83haQAw',
    appId: '1:516346071617:ios:f2accae235e80e1d4a14c0',
    messagingSenderId: '516346071617',
    projectId: 'aviation-project-46322',
    storageBucket: 'aviation-project-46322.appspot.com',
    iosBundleId: 'com.example.aviationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR83I1XGeJUjiMKTEe9sw34dYl83haQAw',
    appId: '1:516346071617:ios:f2accae235e80e1d4a14c0',
    messagingSenderId: '516346071617',
    projectId: 'aviation-project-46322',
    storageBucket: 'aviation-project-46322.appspot.com',
    iosBundleId: 'com.example.aviationProject',
  );
}
